"""empty message

Revision ID: 101514f15fbc
Revises: 454c25be1f8b
Create Date: 2018-08-06 11:29:30.499296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '101514f15fbc'
down_revision = '454c25be1f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('href', sa.String(length=200), nullable=True),
    sa.Column('picsrc', sa.String(length=200), nullable=True),
    sa.Column('tag_list', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('years', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('intro', sa.TEXT(), nullable=True),
    sa.Column('nums', sa.String(length=100), nullable=True),
    sa.Column('star_list', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movie_scrapy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_scrapy',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('href', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('picsrc', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('tag_list', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('years', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('intro', mysql.TEXT(), nullable=True),
    sa.Column('nums', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('star_list', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('movie')
    # ### end Alembic commands ###
